### ISSUE TITLE
invalid DISPLAY

### ISSUE THREAD

**Issue by cwpearson** [c3sr/scope_plot#11]
when running `scope_plot bar broadcast.json bytes bytes_per_second test.pdf --filter-name="NCCL_ops_broadcast/.*/0/0"` on 962162da9a02069e4505eb7c788ceb203d082e04 on minsky1

**Comment by hashash2** [comment]
I get 
![image](https://user-images.githubusercontent.com/16603052/44932959-f6779b00-ad2c-11e8-90e1-28d0e4126362.png)

**Comment by cwpearson** [comment]
Possibly:

```python
if 'DISPLAY' not in os.environ: matplotlib.use('agg')
```

after https://github.com/c3sr/scope_plot/blob/962162da9a02069e4505eb7c788ceb203d082e04/scope_plot/backends/matplotlib.py#L6

**Comment by cwpearson** [comment]
b4b6e717957fed9fecbca16c1085314784e934eb
