### ISSUE TITLE
pip install e . on power9

### ISSUE THREAD

**Issue by hashash2** [c3sr/scope_plot#13]
pip install e . on power9 causes
![image](https://user-images.githubusercontent.com/16603052/45114838-b3923a80-b113-11e8-8e0a-d5f69b4c155f.png)

**Comment by cwpearson** [comment]
what is `git log -n1`

**Comment by cwpearson** [comment]
I think this actually due to not supporting python3.4. I'll add some instructions for setting up a pyenv / pipenv environment to the documentation.
